# Generated by Django 4.1.6 on 2023-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_mark', models.CharField(max_length=20)),
                ('full_mark', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('base_fuel_consumption', models.FloatField()),
                ('special_fuel_consumption', models.FloatField()),
                ('base_tank_volume', models.IntegerField()),
                ('special_tank_volume', models.IntegerField()),
                ('brand_motor_oil', models.CharField(max_length=20)),
            ],
        ),
    ]
